# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
      - run:
          command: |
            sudo pip install pipenv
            pipenv install pylint==2.3.1
            pipenv install coverage==4.5.4
            pipenv install codecov
      - save_cache:
          paths:
            - "Pipfile.lock"
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: run pylint
          command: |
            pipenv run python3 -m continuous_integration --pylint
      - run:
          name: run unit tests with coverage check
          command: |
            pipenv run python3 -m continuous_integration --tests
      - run:
          name: run code cov
          command: |
            pipenv run codecov
